// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATaqYINdEfhIqX_ZIsHua0FWws7t78sVQ',
    appId: '1:642212017386:web:aebeeff22528b95f5e1393',
    messagingSenderId: '642212017386',
    projectId: 'meals-app-a17d8',
    authDomain: 'meals-app-a17d8.firebaseapp.com',
    storageBucket: 'meals-app-a17d8.appspot.com',
    measurementId: 'G-MSL24FCNH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsg8wElIcF30kLE5Ow0IUruVbyDZCjHYg',
    appId: '1:642212017386:android:b4a13062e146fa655e1393',
    messagingSenderId: '642212017386',
    projectId: 'meals-app-a17d8',
    storageBucket: 'meals-app-a17d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKaQeeLDinqqIo7D8YQk9joaa8_uX0mU',
    appId: '1:642212017386:ios:f5c3c64a9c52f81a5e1393',
    messagingSenderId: '642212017386',
    projectId: 'meals-app-a17d8',
    storageBucket: 'meals-app-a17d8.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKaQeeLDinqqIo7D8YQk9joaa8_uX0mU',
    appId: '1:642212017386:ios:3ba869d4ed3cecc95e1393',
    messagingSenderId: '642212017386',
    projectId: 'meals-app-a17d8',
    storageBucket: 'meals-app-a17d8.appspot.com',
    iosBundleId: 'com.example.mealsApp.RunnerTests',
  );
}
